Creating window glfw
Epochs: 1, Loss: 12097261568.0, lr: 0.004, time: 50, False
Epochs: 2, Loss: 11969655808.0, lr: 0.004, time: 50, False
Epochs: 3, Loss: 11843019776.0, lr: 0.004, time: 50, False
Epochs: 4, Loss: 11718264832.0, lr: 0.004, time: 50, False
Epochs: 5, Loss: 11595679744.0, lr: 0.004, time: 50, False
Epochs: 6, Loss: 11474675712.0, lr: 0.004, time: 50, False
Epochs: 7, Loss: 11352525824.0, lr: 0.004, time: 50, False
Epochs: 8, Loss: 11230081024.0, lr: 0.004, time: 50, False
Epochs: 9, Loss: 11102415872.0, lr: 0.004, time: 50, False
Epochs: 10, Loss: 10982726656.0, lr: 0.004, time: 50, False
Epochs: 11, Loss: 10858237952.0, lr: 0.004, time: 50, False
Epochs: 12, Loss: 10729877504.0, lr: 0.004, time: 50, False
Epochs: 13, Loss: 10599510016.0, lr: 0.004, time: 50, False
Epochs: 14, Loss: 10462222336.0, lr: 0.004, time: 50, False
Epochs: 15, Loss: 10330706944.0, lr: 0.004, time: 50, False
Epochs: 16, Loss: 10188320768.0, lr: 0.004, time: 50, False
Epochs: 17, Loss: 10040872960.0, lr: 0.004, time: 50, False
Epochs: 18, Loss: 9895745536.0, lr: 0.004, time: 50, False
Epochs: 19, Loss: 9743262720.0, lr: 0.004, time: 50, False
Epochs: 20, Loss: 9588301824.0, lr: 0.004, time: 50, False
########## Saving Trace ##########
Traceback (most recent call last):
  File "tv_value_synthesis_trajopt_cartpole.py", line 221, in <module>
    loss.backward()
  File "/home/daniel/.local/share/virtualenvs/Mujoco_Python_Sandbox-gNKKWzd6/lib/python3.7/site-packages/torch/_tensor.py", line 488, in backward
    self, gradient, retain_graph, create_graph, inputs=inputs
  File "/home/daniel/.local/share/virtualenvs/Mujoco_Python_Sandbox-gNKKWzd6/lib/python3.7/site-packages/torch/autograd/__init__.py", line 199, in backward
    allow_unreachable=True, accumulate_grad=True)  # Calls into the C++ engine to run the backward pass
KeyboardInterrupt
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "tv_value_synthesis_trajopt_cartpole.py", line 261, in <module>
    model_scripted = torch.jit.script(dyn_system.value_func.to('cpu'))  # Export to TorchScript
  File "/home/daniel/.local/share/virtualenvs/Mujoco_Python_Sandbox-gNKKWzd6/lib/python3.7/site-packages/torch/jit/_script.py", line 1287, in script
    obj, torch.jit._recursive.infer_methods_to_compile
  File "/home/daniel/.local/share/virtualenvs/Mujoco_Python_Sandbox-gNKKWzd6/lib/python3.7/site-packages/torch/jit/_recursive.py", line 476, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, stubs_fn)
  File "/home/daniel/.local/share/virtualenvs/Mujoco_Python_Sandbox-gNKKWzd6/lib/python3.7/site-packages/torch/jit/_recursive.py", line 542, in create_script_module_impl
    create_methods_and_properties_from_stubs(concrete_type, method_stubs, property_stubs)
  File "/home/daniel/.local/share/virtualenvs/Mujoco_Python_Sandbox-gNKKWzd6/lib/python3.7/site-packages/torch/jit/_recursive.py", line 393, in create_methods_and_properties_from_stubs
    concrete_type._create_methods_and_properties(property_defs, property_rcbs, method_defs, method_rcbs, method_defaults)
RuntimeError:
attribute lookup is not defined on python value of type 'SimulationParams':
  File "tv_value_synthesis_trajopt_cartpole.py", line 74
    def forward(self, t, x):
        time = torch.ones((sim_params.nsim, 1, 1)).to(device) * t
                           ~~~~~~~~~~~~~~~ <--- HERE
        aug_x = torch.cat((x, time), dim=2)
        return self.nn(aug_x)